/****** Object:  Database [musicSystem]    Script Date: 21.04.2021 16:58:22 ******/
CREATE DATABASE [musicSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'musicSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\musicSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'musicSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\musicSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [musicSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [musicSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [musicSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [musicSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [musicSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [musicSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [musicSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [musicSystem] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [musicSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [musicSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [musicSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [musicSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [musicSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [musicSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [musicSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [musicSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [musicSystem] SET  ENABLE_BROKER 
GO
ALTER DATABASE [musicSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [musicSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [musicSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [musicSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [musicSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [musicSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [musicSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [musicSystem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [musicSystem] SET  MULTI_USER 
GO
ALTER DATABASE [musicSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [musicSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [musicSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [musicSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [musicSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [musicSystem] SET QUERY_STORE = OFF
GO
USE [musicSystem]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[AccountID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](255) NOT NULL,
	[LastName] [varchar](255) NOT NULL,
	[Email] [varchar](255) NOT NULL,
	[Username] [varchar](255) NOT NULL,
	[PasswordHash] [binary](32) NOT NULL,
	[PasswordSalt] [binary](32) NOT NULL,
	[Created] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Account_Storage]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account_Storage](
	[AccountID] [int] NOT NULL,
	[StorageID] [int] NOT NULL,
	[JsonData] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC,
	[StorageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[playlist]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[playlist](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[AccountID] [int] NOT NULL,
	[Sync] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PlaylistSong]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlaylistSong](
	[PlaylistsId] [int] NOT NULL,
	[SongsId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PlaylistsId] ASC,
	[SongsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Song]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Song](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [varchar](255) NOT NULL,
	[AccountID] [int] NOT NULL,
	[StorageID] [int] NULL,
	[StorageSongID] [varchar](max) NULL,
	[Name] [varchar](255) NULL,
	[LengthSec] [int] NULL,
	[Author] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Storage]    Script Date: 21.04.2021 16:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Storage](
	[StorageID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StorageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[playlist] ADD  DEFAULT ((0)) FOR [Sync]
GO
ALTER TABLE [dbo].[Account_Storage]  WITH CHECK ADD FOREIGN KEY([AccountID])
REFERENCES [dbo].[Account] ([AccountID])
GO
ALTER TABLE [dbo].[Account_Storage]  WITH CHECK ADD FOREIGN KEY([StorageID])
REFERENCES [dbo].[Storage] ([StorageID])
GO
ALTER TABLE [dbo].[playlist]  WITH CHECK ADD FOREIGN KEY([AccountID])
REFERENCES [dbo].[Account] ([AccountID])
GO
ALTER TABLE [dbo].[PlaylistSong]  WITH CHECK ADD  CONSTRAINT [FK__playlist___Playl__30F848ED] FOREIGN KEY([PlaylistsId])
REFERENCES [dbo].[playlist] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PlaylistSong] CHECK CONSTRAINT [FK__playlist___Playl__30F848ED]
GO
ALTER TABLE [dbo].[PlaylistSong]  WITH CHECK ADD  CONSTRAINT [FK__playlist___SongI__31EC6D26] FOREIGN KEY([SongsId])
REFERENCES [dbo].[Song] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PlaylistSong] CHECK CONSTRAINT [FK__playlist___SongI__31EC6D26]
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD FOREIGN KEY([AccountID])
REFERENCES [dbo].[Account] ([AccountID])
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD FOREIGN KEY([StorageID])
REFERENCES [dbo].[Storage] ([StorageID])
GO
USE [master]
GO
ALTER DATABASE [musicSystem] SET  READ_WRITE 
GO
